---
title: "Relatório Estadão Dados"
---

```{r , cache=TRUE, echo=FALSE}
library(memisc)
setwd("./arquivos_originais")
source("../analisa_microdados.R")
options(stringsAsFactors = FALSE)

perg_maio = c("p1","p2","p3","p4","p7a","p7b","p10","p11","p13")
trad_maio = c("vida_hoje","interesse","intencao_espontanea","intencao_estimulada","2turno_aecio","2turno_campos","avaliacao_governo","aprova_dilma","desejo_mudanca")
perg_abril = c("p1","p2","p3","p4","p9a","p9c","p12","p13","p15")
trad_abril = c("vida_hoje","interesse","intencao_espontanea","intencao_estimulada","2turno_aecio","2turno_campos","avaliacao_governo","aprova_dilma","desejo_mudanca")
abril = cria_arquivo("ibopeabr2014.sav",perg_abril,trad_abril,TRUE)
maio = cria_arquivo("ibopemai2014.sav",perg_maio,trad_maio,TRUE)
resultado_abril = calcula_tudo(abril,"2014-04-14")
resultado_maio = calcula_tudo(maio,"2014-05-19")
teste_amostra_maio = analise_amostra(maio)
teste_amostra_abril = analise_amostra(abril)
```

```{r loop, result='asis', fig.cap=rep('',5), cache=TRUE, echo=FALSE }
library(memisc)
library(ggplot2)
library(reshape2)
setwd("./arquivos_originais")
colors <- c("darkblue", "red")

for (perg in names(teste_amostra_abril)) {
  d1 = teste_amostra_abril[[perg]]
  d2 = teste_amostra_maio[[perg]]
  names(d1) = paste(names(teste_amostra_abril[[perg]]),deparse(substitute(abril)),sep='_')
  names(d2) = paste(names(teste_amostra_maio[[perg]]),deparse(substitute(maio)),sep='_')
  imprimir = cbind(d1,d2)
  print(imprimir)
  tab = t(as.matrix(imprimir))
  barX = barplot(tab, beside=TRUE, axis.lty=1, col=colors)
  text(cex=.5,x=barX,y=tab+par("cxy")[2]/2, round(tab,2), xpd=TRUE)
  plot.new()
  legend("center", "groups", colnames(imprimir), fill=colors)
  cat("\n!")
}

```
